Improved error handling
mkmurn now checks that at least one directory has been processed.
Otherwise murncalc will attempt to pass a file with zero data points to
murn.

murncalc has been updated so that errors received from mkmurn are
captured and passed through to STDERR.

diff --git a/murncalc b/murncalc
--- a/murncalc
+++ b/murncalc
@@ -1,5 +1,9 @@
 #! /bin/bash
 
-mkmurn > murn.in
+errmsg=$( { mkmurn > murn.in ;} 2>&1 ) # STDERR is redirected to STDOUT before being captured in $errmsg
+if [ "$?" -ne 0 ]; then
+    echo "Error in 'mkmurn': $errmsg" >&2
+    exit 1
+fi
 murn < murn.in > murn.out
 egrep "^alat" murn.out
